# 开发环境 Dockerfile - 前端
FROM zhcoder-docker-registry.com:8000/official/node:20-alpine
RUN npm config set registry https://registry.npmmirror.com 

# 安装 pnpm
RUN npm install -g pnpm

# 设置工作目录
WORKDIR /app

# 复制 package.json 文件
COPY frontend/package.json frontend/pnpm-lock.yaml ./frontend/

# 安装依赖
RUN cd frontend && pnpm install --frozen-lockfile

# 复制前端源代码
COPY frontend ./frontend

# 设置环境变量
ENV NODE_ENV=development

# 暴露端口
EXPOSE 5173

# 启动开发服务器
CMD cd frontend && npm run dev -- --host